# Generated by Django 3.2.5 on 2021-08-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('BGH', 'BGH'), ('Philips', 'Philips'), ('LG', 'LG'), ('Noblex', 'Noblex'), ('Atma', 'Atma')], default='BGH', max_length=64)),
                ('garantia', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=64)),
                ('detalle', models.CharField(max_length=200)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('dni', models.IntegerField()),
                ('pedidos', models.ManyToManyField(blank=True, to='app.Pedido')),
            ],
        ),
    ]
