# Generated by Django 3.2.5 on 2021-08-10 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210810_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_salida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
