# Generated by Django 3.2.5 on 2021-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210810_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='pedido',
            name='comentarios',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Reparado', 'Reparado')], default='En proceso', max_length=64),
        ),
    ]
