# Generated by Django 3.2.5 on 2021-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pedido_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='marca',
            field=models.CharField(choices=[('BGH', 'BGH'), ('Philips', 'Philips'), ('LG', 'LG'), ('Noblex', 'Noblex'), ('Atma', 'Atma'), ('Otro', 'Otro')], default='BGH', max_length=64),
        ),
    ]
