# Generated by Django 3.2.5 on 2021-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_pedido_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Reparado', 'Reparado'), ('Listo para retirar', 'Listo para retirar')], default='En proceso', max_length=64),
        ),
    ]
