# Generated by Django 3.2.5 on 2021-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidoNoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('celular', models.CharField(max_length=10)),
                ('retiro_en_domicilio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2)),
                ('comentarios', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(default='', max_length=64),
        ),
    ]
