# Generated by Django 3.2.5 on 2021-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
